#!/usr/bin/env python3
"""Convert an Aurora wallpaper PNG to the compact resource used by the FSOS desktop."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "aurora-night-source.png"
OUTPUT = ROOT / "user" / "aurora_wallpaper.h"
PREVIEW = ROOT / "assets" / "aurora-night-320x200.png"
WIDTH, HEIGHT, COLORS = 320, 200, 128


def values(data, width=16):
    return "\n".join(
        "    " + ", ".join(str(v) for v in data[i:i + width]) + ","
        for i in range(0, len(data), width)
    )


def main():
    image = Image.open(SOURCE).convert("RGB")
    # 16:10 center crop preserves the central Aurora form and the lake reflection.
    source_ratio = image.width / image.height
    target_ratio = WIDTH / HEIGHT
    if source_ratio > target_ratio:
        crop_w = round(image.height * target_ratio)
        left = (image.width - crop_w) // 2
        image = image.crop((left, 0, left + crop_w, image.height))
    else:
        crop_h = round(image.width / target_ratio)
        top = (image.height - crop_h) // 2
        image = image.crop((0, top, image.width, top + crop_h))
    image = image.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)
    indexed = image.quantize(colors=COLORS, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.FLOYDSTEINBERG)
    palette = indexed.getpalette()[:COLORS * 3]
    pixels = list(indexed.getdata())
    indexed.convert("RGB").save(PREVIEW)
    OUTPUT.write_text(
        "// Generated by tools/wallpaper_convert.py; do not edit manually.\n"
        "#ifndef AURORA_WALLPAPER_RESOURCE_H\n#define AURORA_WALLPAPER_RESOURCE_H\n\n"
        "#include <stdint.h>\n\n"
        "#define AURORA_WALLPAPER_W 320\n"
        "#define AURORA_WALLPAPER_HEIGHT 200\n"
        "#define AURORA_WALLPAPER_COLORS 128\n\n"
        "static const uint8_t aurora_wallpaper_palette[AURORA_WALLPAPER_COLORS * 3] = {\n"
        + values(palette) + "\n};\n\n"
        "static const uint8_t aurora_wallpaper_pixels[AURORA_WALLPAPER_W * AURORA_WALLPAPER_HEIGHT] = {\n"
        + values(pixels, 32) + "\n};\n\n#endif // AURORA_WALLPAPER_RESOURCE_H\n",
        encoding="ascii",
    )
    print(f"wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes); preview {PREVIEW}")


if __name__ == "__main__":
    main()
