# detect_host.cmake - 宿主平台注入 (cross_platform 任务 1.5)
# 在 CMake 配置期按宿主平台设置 NASM 格式 / NASM 调试格式 / 链接模拟,
# 供 first/CMakeLists.txt 消费。IDE 辅助路径仍非产物权威路径 (权威 = tools/fsos.py)。

if(NOT DEFINED HOST_NASM_FMT)
  if(CMAKE_SYSTEM_NAME MATCHES "Linux|Darwin")
    set(HOST_NASM_FMT_64 elf64)
    set(HOST_NASM_FMT_32 elf32)
    set(HOST_LD_EMU_64 elf_x86_64)
    set(HOST_LD_EMU_32 elf_i386)
    set(HOST_NASM_DBG "-g -F dwarf")
    set(HOST_ASM_DEFS "")
  else()
    set(HOST_NASM_FMT_64 win64)
    set(HOST_NASM_FMT_32 win32)
    set(HOST_LD_EMU_64 i386pep)
    set(HOST_LD_EMU_32 i386pe)
    set(HOST_NASM_DBG "-g -F cv8")
    set(HOST_ASM_DEFS "-d MINGW -d MINGW64")
  endif()
endif()

# 默认 64 位链路; 需 32 位构建时 -DARCH=x86
if(NOT DEFINED ARCH)
  set(ARCH x64)
endif()
if(ARCH STREQUAL "x86")
  set(HOST_NASM_FMT ${HOST_NASM_FMT_32})
  set(HOST_LD_EMU ${HOST_LD_EMU_32})
  set(HOST_MFLAG -m32)
else()
  set(HOST_NASM_FMT ${HOST_NASM_FMT_64})
  set(HOST_LD_EMU ${HOST_LD_EMU_64})
  set(HOST_MFLAG -m64)
endif()